baseURL: "https://demo.universtar.org"
languageCode: "en"
title: "Universtar"

params:
  heroTitle: "Universtar"
  repoLink: "https://github.com/universtar-org/universtar"
  project:
    defaultDescription: "No description provided."

languages:
  en:
    languageName: English
  zh:
    languageName: "中文"

build:
  writeStats: true
  noJSConfigInAssets: true
  buildStats:
    enable: true
  cachebusters:
    - source: 'assets/notwatching/hugo_stats\.json'
      target: css
    - source: '(postcss|tailwind)\.config\.js'
      target: css

module:
  mounts:
    - source: assets
      target: assets
    - disableWatch: true
      source: hugo_stats.json
      target: assets/notwatching/hugo_stats.json
